POST localhost:4000/dummyTemplate

###

GRAPHQL localhost:4000/graphql

query Categories {
    categories {id name auditLog { id action data createdAt} children {id name}}
}

###
GRAPHQL localhost:4000/graphql

mutation addCategory {
  addCategory(input: {name: "Category"}) { id name }
}

###
GRAPHQL localhost:4000/graphql

mutation addCategoryWithParent {
  addCategory(input: {name: "Category with parent", parentId: 1}) { id name }
}

###
GRAPHQL localhost:4000/graphql

query categorySearch {
  categories(name: "parent") { id name createdAt parent {id} auditLog {id action data}}
}

###
GRAPHQL localhost:4000/graphql

mutation SetPropertyValue
{
setPropertyValue(input: {itemId: 1, propertyId: 1, value: "Value!"})
}

###
POST localhost:4000/dummyTemplate
